# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24c7e49f4cec3ce7a1d123d7eb910460353a294800a5b4d938f8a8f2d362cc782300bb88e60a89fdabdb84d913367f20b253c4465914081323d116da3d3aea29

test:
  secret_key_base: 2b26946e4441cdcd8cc8b96ef47cb7d1dd98c4e85ed262863dc4cdbf7b619960224043f5eb61b2c3244ad3adf79ac88ce655325323b0f561e7b71c9f55cbbbbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
